name: Production Deployment

on:
  push:
    branches:
      - ch-deploy-app

  release:
    types:
      - released
      - prereleased
  workflow_dispatch:

jobs:
  build_and_deploy_staging:
    outputs:
      image: ${{ env.IMAGE }}
      tag: ${{ env.TAG }}
      release_version: ${{ env.version }}

    runs-on: ubuntu-latest
    env:
      image: cranecloud/cranecloud-cms
      namespace: cranecloud-prod

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ch-deploy-app

      - name: Get version
        id: version
        run: |
          if [[ $GITHUB_EVENT_NAME == "release" ]]; then
            echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          else
            echo "version=dev-$(date +'%Y%m%d')-$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          fi

      - name: Update CHANGELOG.md
        if: github.event_name == 'release'
        run: |
          # Get the release version and date
          VERSION=${GITHUB_REF#refs/tags/}
          DATE=$(date +'%Y-%m-%d')

          # Get the release notes from the GitHub release
          RELEASE_NOTES=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/releases/tags/$VERSION" | \
            jq -r '.body')

          # Create the new version section
          NEW_SECTION="## [$VERSION] - $DATE\n\n"

          # Parse the release notes and categorize them
          if echo "$RELEASE_NOTES" | grep -q "### Added"; then
            NEW_SECTION+="### Added\n"
            NEW_SECTION+=$(echo "$RELEASE_NOTES" | sed -n '/### Added/,/^$/p' | sed '1d')
            NEW_SECTION+="\n"
          fi

          if echo "$RELEASE_NOTES" | grep -q "### Changed"; then
            NEW_SECTION+="### Changed\n"
            NEW_SECTION+=$(echo "$RELEASE_NOTES" | sed -n '/### Changed/,/^$/p' | sed '1d')
            NEW_SECTION+="\n"
          fi

          if echo "$RELEASE_NOTES" | grep -q "### Fixed"; then
            NEW_SECTION+="### Fixed\n"
            NEW_SECTION+=$(echo "$RELEASE_NOTES" | sed -n '/### Fixed/,/^$/p' | sed '1d')
            NEW_SECTION+="\n"
          fi

          if echo "$RELEASE_NOTES" | grep -q "### Security"; then
            NEW_SECTION+="### Security\n"
            NEW_SECTION+=$(echo "$RELEASE_NOTES" | sed -n '/### Security/,/^$/p' | sed '1d')
            NEW_SECTION+="\n"
          fi

          # Update the CHANGELOG.md
          awk -v new="$NEW_SECTION" '
            /^## \[Unreleased\]/ {
              print;
              print "";
              print new;
              next;
            }
            { print }
          ' CHANGELOG.md > CHANGELOG.md.new

          mv CHANGELOG.md.new CHANGELOG.md

          # Commit and push the changes
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add CHANGELOG.md
          git commit -m "docs: update CHANGELOG.md for $VERSION"
          git push

      - name: Install (Buildx)
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login (GCP)
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.CREDENTIALS_JSON }}

      - name: Install (Gcloud)
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: crane-cloud-274413
          install_components: 'gke-gcloud-auth-plugin'

      - name: Get Kubernetes credentials
        run: |
          gcloud container clusters get-credentials staging-cluster --zone us-central1-a

      - id: meta
        name: Tag
        uses: docker/metadata-action@v3
        with:
          flavor: |
            latest=auto
            prefix=
          images: ${{ env.image }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      - name: Add Env vars
        env:
          SANITY_STUDIO_PROJECT_ID: ${{ secrets.SANITY_STUDIO_PROJECT_ID }}
          SANITY_STUDIO_DATASET: ${{ secrets.SANITY_STUDIO_DATASET }}
        run: |
          chmod +x ./.github/workflows/bin/create_envs.sh
          ./.github/workflows/bin/create_envs.sh

      - name: Build
        uses: docker/build-push-action@v5
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: .
          labels: ${{ steps.meta.outputs.labels }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}

      - id: export
        name: Export
        uses: actions/github-script@v7
        with:
          script: |
            const metadata = JSON.parse(`${{ steps.meta.outputs.json }}`)
            const fullUrl = metadata.tags.find((t) => t.includes(':sha-'))
            if (fullUrl == null) {
              core.error('Unable to find sha tag of image')
            } else {
              const tag = fullUrl.split(':')[1]
              core.exportVariable('IMAGE', fullUrl)
              core.exportVariable('TAG', tag)
            }

      - name: Update deployment image
        run: |
          kubectl set image deployment/cranecloud-cms cranecloud-cms=${{ env.image }}:${{ env.TAG }} -n $namespace

      - name: Verify deployment
        run: |
          echo "Waiting for deployment to roll out..."
          kubectl rollout status deployment/cranecloud-cms -n $namespace --timeout=300s

          echo "Verifying deployment health..."
          kubectl get pods -n $namespace -l app=cranecloud-cms -o wide

          # Add basic health check
          POD_NAME=$(kubectl get pods -n $namespace -l app=cranecloud-cms -o jsonpath="{.items[0].metadata.name}")
          kubectl exec -n $namespace $POD_NAME -- curl -f http://localhost:80/health || exit 1

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
